AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  StorageBucket:
    Type: AWS::S3::Bucket
    Properties:
      CorsConfiguration:
        CorsRules:
        - AllowedHeaders: ["*"]
          AllowedMethods: ["POST"]
          AllowedOrigins: ["*"]

  WebsiteBucket:
    Type: AWS::S3::Bucket
    # Properties:
      #AccessControl: PublicRead
      #WebsiteConfiguration:
      #  IndexDocument: index.html

  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            AWS:
            - !GetAtt WebInstallerFunctionRole.Arn
          Action:
          - s3:PutObjectAcl
          - s3:DeleteObject
          Resource: !Sub arn:aws:s3:::${WebsiteBucket}/*
        - Action:
            - s3:GetObject
          Effect: Allow
          Resource: !Join [ "", [ "arn:aws:s3:::", !Ref WebsiteBucket, "/*" ] ]
          Principal:
            CanonicalUser: !GetAtt TheCloudFrontOriginAccessIdentity.S3CanonicalUserId

  WebsiteCloudfront:
    Type: AWS::CloudFront::Distribution
    DependsOn:
    - WebsiteBucket
    Properties:
      DistributionConfig:
        Comment: Cloudfront Distribution pointing to S3 bucket
        Origins:
        - DomainName: !Join [ "", [ !Ref WebsiteBucket, ".s3-eu-west-1.amazonaws.com" ] ]
          Id: S3Origin
          S3OriginConfig:
              OriginAccessIdentity:
                !Join [ "", [ "origin-access-identity/cloudfront/", !Ref TheCloudFrontOriginAccessIdentity ] ]
        Enabled: true
        HttpVersion: 'http2'
        DefaultRootObject: index.html
        Aliases:
        - 'fichier.tendanci.eu'
        DefaultCacheBehavior:
          AllowedMethods:
          - GET
          - HEAD
          - OPTIONS
          Compress: true
          TargetOriginId: S3Origin
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: 'arn:aws:acm:us-east-1:587437228810:certificate/86387e72-33a0-480c-a1c8-e757ed361860'
          SslSupportMethod: sni-only
  TheCloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub 'CloudFront OAI for fichier.tendanci.eu'
  # WebsiteDNSName:
  #   Type: AWS::Route53::RecordSetGroup
  #   Properties:
  #     HostedZoneName: 'tendanci.eu.'
  #     RecordSets:
  #     - Name: 'fichier.tendanci.eu'
  #       Type: A
  #       AliasTarget:
  #         HostedZoneId: Z2IP282KTO21XX
  #         DNSName: !GetAtt [WebsiteCloudfront, DomainName]

  Table:
    Type: AWS::Serverless::SimpleTable

  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: fichier-tendanci-eu
      AutoVerifiedAttributes:
      - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: false
          RequireNumbers: false
          RequireSymbols: false
          RequireUppercase: false

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool

  Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda.handler
      Runtime: python3.6
      CodeUri: ./lambda.zip
      Environment:
        Variables:
          BUCKET: !Ref StorageBucket
          REGION: !Ref AWS::Region
          TABLE: !Ref Table
      Policies:
      - S3CrudPolicy:
          BucketName: !Ref StorageBucket
      - DynamoDBCrudPolicy:
          TableName: !Ref Table

  WebInstallerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: web_installer.handler
      Runtime: python3.6
      CodeUri: ./lambda.zip
      Environment:
        Variables:
          BUCKET: !Ref WebsiteBucket
          DIR: web
      Policies:
      - S3CrudPolicy:
          BucketName: !Ref WebsiteBucket

  WebInstaller:
    Type: Custom::WebInstaller
    DependsOn: WebsiteBucketPolicy
    Properties:
      ServiceToken: !GetAtt WebInstallerFunction.Arn
      ApiUrl: !Sub https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
      UserPoolId: !Ref UserPool
      ClientId: !Ref UserPoolClient

  ApiGatewayToLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal: {Service: [apigateway.amazonaws.com]}
          Action: "sts:AssumeRole"
      Policies:
      - PolicyName: ApiGatewayToLambdaPolicy
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Action: ["lambda:InvokeFunction"]
            Resource: !GetAtt Function.Arn

  ServerlessRestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionBody:
        swagger: "2.0"

        basePath: "/"

        produces:
        - application/json

        schemes:
        - "https"

        info:
          version: "1.0"
          title: "fichier-tendanci-eu"

        securityDefinitions:
          fichier-tendanci-eu:
            type: "apiKey"
            name: "Authorization"
            in: "header"
            x-amazon-apigateway-authtype: "cognito_user_pools"
            x-amazon-apigateway-authorizer:
              type: "cognito_user_pools"
              providerARNs:
              - !GetAtt UserPool.Arn

        paths:
          /{action}:
            x-amazon-apigateway-any-method:
              security:
              - fichier-tendanci-eu: []
              x-amazon-apigateway-integration:
                credentials: !GetAtt ApiGatewayToLambdaRole.Arn
                type: "aws_proxy"
                httpMethod: "POST"
                uri: !GetAtt Function.Arn
                uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${Function.Arn}/invocations
                passthroughBehavior: "when_no_match"
                responses:
                  "default":
                    statusCode: "200"
                    responseParameters:
                      method.response.header.Access-Control-Allow-Headers : "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
                      method.response.header.Access-Control-Allow-Methods : "'*'"
                      method.response.header.Access-Control-Allow-Origin : "'*'"
                  "BAD.*":
                    statusCode: "400"
                    responseParameters:
                      method.response.header.Access-Control-Allow-Origin : "'*'"
                  "INT.*":
                    statusCode: "500"
                    responseParameters:
                      method.response.header.Access-Control-Allow-Origin : "'*'"
              responses:
                "200":
                  description: Default response for CORS method
                  headers:
                    Access-Control-Allow-Headers:
                      type: "string"
                    Access-Control-Allow-Methods:
                      type: "string"
                    Access-Control-Allow-Origin:
                      type: "string"
                "400":
                  description: Bad request
                  headers:
                    Access-Control-Allow-Origin:
                      type: "string"
                "500":
                  description: Internal error
                  headers:
                    Access-Control-Allow-Origin:
                      type: "string"
            options:
              summary: CORS support
              description: Enable CORS by returning correct headers
              consumes:
              - application/json
              produces:
              - application/json
              tags:
              - CORS
              x-amazon-apigateway-integration:
                type: mock
                requestTemplates:
                  application/json: |
                    {
                      "statusCode" : 200
                    }
                responses:
                  "default":
                    statusCode: "200"
                    responseParameters:
                      method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
                      method.response.header.Access-Control-Allow-Methods: "'*'"
                      method.response.header.Access-Control-Allow-Origin: "'*'"
                    responseTemplates:
                      application/json: |
                        {}

              responses:
                "200":
                  description: Default response for CORS method
                  headers:
                    Access-Control-Allow-Headers:
                      type: "string"
                    Access-Control-Allow-Methods:
                      type: "string"
                    Access-Control-Allow-Origin:
                      type: "string"

            options:
              summary: CORS support
              description: Enable CORS by returning correct headers
              consumes:
              - application/json
              produces:
              - application/json
              tags:
              - CORS
              x-amazon-apigateway-integration:
                type: mock
                requestTemplates:
                  application/json: |
                    {
                      "statusCode" : 200
                    }
                responses:
                  "default":
                    statusCode: "200"
                    responseParameters:
                      method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
                      method.response.header.Access-Control-Allow-Methods: "'*'"
                      method.response.header.Access-Control-Allow-Origin: "'*'"
                    responseTemplates:
                      application/json: |
                        {}

              responses:
                "200":
                  description: Default response for CORS method
                  headers:
                    Access-Control-Allow-Headers:
                      type: "string"
                    Access-Control-Allow-Methods:
                      type: "string"
                    Access-Control-Allow-Origin:
                      type: "string"

Outputs:
  Website:
    Description: Website URL
    Value: !GetAtt WebsiteBucket.WebsiteURL
